<? 
header('content-type: application/json; charset=utf-8');
header("access-control-allow-origin: *");
if(mt_rand(0,1) > 0.5) { 
?>

{"query":"SELECT 1  FROM manual_updates  WHERE pubdate > 0   && borough='Kensington and Chelsea Borough Council' ORDER BY pubdate DESC LIMIT 4","results":[{"id":"01","title":"NHS Winter: Weekly A&E tracker. This winter, the BBC has been tracking the data so that you can find out how your nearest major A&E in England is coping week by week.","ward":"City Living Local Life (20th Jan)","short_url":"http://bit.ly/1bbAtHk","tags":["Tags: Health",""],"human_date":"20th Jan 2014"},{"id":"02","title":"Shared video: A look into the lives of the people who live at the 'wrong end' of the King's Road.","ward":"World's End, Chelsea on Facebook (21st Jan)","short_url":"http://on.fb.me/1mECRP0","tags":["Tag: Local politics",""],"human_date":"17th Jan 2014"},{"id":"03","title":"Epic CiC K&C Youth Support have a new website !","ward":"Epiccic on Facebook (21st Jan)","short_url":"facebook.com/epiccic","tags":["Tags: Youth",""],"human_date":"20th Jan 2014"},{"id":"04","title":"The Six cafe style gatherings at St Lukes Redcliffe Gardens starting a new year and a new series. ","description":"","ward":"Queensofkensal via Facebook (20th Jan)","short_url":"http://on.fb.me/1dOhkRN","":"","tags":["Tags: Church","Community Event"],"human_date":"20th Jan 2014"}]}

<? } else { ?>

{"query":"SELECT 2  FROM manual_updates  WHERE pubdate > 0   && borough='Kensington and Chelsea Borough Council' ORDER BY pubdate DESC LIMIT 4","results":[{"id":"01","title":"House of commons debate of Earl's Court Exhibition Centre","ward":"saveearlscourt.com (21th Jan)","short_url":"http://bit.ly/1cPC854","tags":["Tags: Planning",""],"human_date":"21th Jan 2014"},{"id":"02","title":"So pleased to welcome #Meantime to our draught selection! Come in for a pint of the London Lager or Pale Ale","ward":"The Eagle Ladbroke Grove (21st Jan)","short_url":"facebook.com/theeagleladbrokegrove","tags":["Tag: Pubs & Bars",""],"human_date":"21st Jan 2014"},{"id":"03","title":"Thank you to The Eagle Pub, Ladbroke Grove - for supporting us, as for every Fish and Chips bought, £1 will be donated to Full of Life! ","ward":"Full of Life Kensington and Chelsea on Facebook (21st Jan)","short_url":"facebook.com/fullofliferbkc","tags":["Tag: Charity","Pubs & Bars"],"human_date":"20th Jan 2014"},{"id":"04","title":"Excited for @NormanJayMBE on Friday! chasing away the wintery blues, tickets still available: ","description":"","ward":"Weloveparadise on Twitter (21st Jan)","short_url":"http://bit.ly/1imeyoM","":"","tags":["Tag: Pubs & Bars",""],"human_date":"20th Jan 2014"}]}
<? }?>
