<? 
header('content-type: application/json; charset=utf-8');
header("access-control-allow-origin: *");
if(mt_rand(0,1) > 0.5) { 
?>
{"query":"SELECT *  FROM manual_updates  WHERE pubdate > 0   && borough='Kensington and Chelsea Borough Council' ORDER BY pubdate DESC LIMIT 4","results":[{"id":"01","title":"Free Training from Healthwatch CWL","ward":"citylivinglocallife.wordpress.com","short_url":"http://bit.ly/1bbAtHk","tags":["Tags: Health","Education"],"human_date":"19th Jan 2014"},{"id":"02","title":"Visit to Kensal Green Cemetery","ward":"http://newtonhouseltd.blogspot.co.uk/","short_url":"http://bit.ly/1f37VCw","tags":["Tags: Local History",""],"human_date":"17th Jan 2014"},{"id":"03","title":"It's the GOODE & WRIGHT Epicerie! This is a pistachio croissant. And it is MINE!","ward":"Portobello and Golborne Road markets via Twitter","short_url":"http://on.fb.me/1dnT3vy","tags":["Tags: Shops","Food"],"human_date":"20th Jan 2014"},{"id":"04","title":"Want to volunteer with us - volunteers do everything from social media to handling phones, administration and also supporting teachers in classes! Use all your skills for a good cause. Come find us at 2 Thorpe Close or call us on 0208 960 2488.","description":"","ward":"Nova New Opportunities via Facebook","short_url":"https://www.facebook.com/novanew","":"","tags":["Tags: Charity","Volunteer"],"human_date":"14th Jan 2014"}]}<?
} else{ 
?>
{"query":"SELECT *  FROM manual_updates  WHERE pubdate > 0   && borough='Kensington and Chelsea Borough Council' ORDER BY pubdate DESC LIMIT 4","results":[{"id":"01","title":"Oportunityfor 12-pitch Youth Market/s on 16 & 23 May in our Arts & Crafts square. Interested? Get in touch! #LYLM2014","ward":"RBKCMarkets via Twitter","short_url":"http://bit.ly/1ajK4RN","tags":["Tags: Markets",""],"human_date":"20th Jan 2014"},{"id":"02","title":"Interested in First Aid Training?","ward":"National HIV Nurses Association via Twitter","short_url":"http://bit.ly/1m8Rxml","tags":["Tags: Community Events","Health"],"human_date":"17th Jan 2014"},{"id":"03","title":"Richard Strange's Cabaret Futura returns tonight to the Paradise by way of Kensal Green!","ward":"The Hub via Twitter","short_url":"http://fb.me/6ud5wfneq ","tags":["Tags: Theatre","Community Event"],"human_date":"20th Jan 2014"},{"id":"04","title":"My Chelsea and Westminster Hospital show, Public Exhibition space, 369 Fulham Road 5th-18th June if you are in the area","description":"","ward":"Krishna Leon ‏via Twitter","short_url":"http://bit.ly/1bApaw1","":"","tags":["Tags: Art",""],"human_date":"20th Jan 2014"}]}<? }?>
